name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        working-directory: ./api
        run: npm i
        
      - name: typeScript build
       working-directory: ./api
       run: npm build 

      - name: Run the project
        working-directory: ./api/dist
        run: npm start
